### ISSUE TITLE
若只使用WebRTC的語音通話功能    

### ISSUE THREAD

**Issue by xjimi** [TaoistKing/chatchat#3]
若只使用語音功能 
在普通的server(aws m3.medium)上運行 1對1的交談模式
如果遇到很多人在同時使用語音功能時 
加開多台server 是否就能改善聊天的品質？
多人1對1語音交談架構 是否適合用webrtc？

**Comment by TaoistKing** [comment]
改善语音质量应该尽量减少链路的丢包率和时延，所以turn server部署在合适的节点上对改善通话质量是有帮助的。
至于是否要多开server取决于你的server负载情况。

**Comment by xjimi** [comment]
你建議是建立自已的 turn server對吧？
那如果用stun:stun.3cx.com:3478 或是其他的stun: 
會有什麼缺點？

如果要自已建立stun 請問有較推薦的方式嗎？

**Comment by TaoistKing** [comment]
Hi xjimi

stun server只是做p2p穿透用，在某些网络条件下，p2p无法建立路由，因此必须在公网部署turn server（使用turn server也可以加速通信建立过程）。
turn server 可以使用coturn：https://github.com/coturn/coturn
部署turn server时原则是为你的数据流选择最佳路由，尽量减少绕转和质量不佳的链路。
请参考这篇文章：https://www.html5rocks.com/en/tutorials/webrtc/infrastructure/

**Comment by xjimi** [comment]
謝謝您的解答~
