### ISSUE TITLE
不開啟Cellular 無法通話

### ISSUE THREAD

**Issue by xjimi** [TaoistKing/chatchat#4]
Hi 
在使用wifi的情況下，不開啟「行動數據」功能，為何無法通話？

類似的問題
https://bugs.chromium.org/p/webrtc/issues/detail?id=4065

**Comment by TaoistKing** [comment]
这个是WebRTC自身的bug吧，我没有碰到过

**Comment by xjimi** [comment]
了解~謝謝您的回復
