### ISSUE TITLE
Text/voice chat doesn't work

### ISSUE THREAD

**Issue by volokha** [TaoistKing/chatchat#6]
Thank you for the really usefull example of webrtc+socket.io
Video call works perfectly, but when I'm clicking on voice or text chat - nothing happens. 
![default](https://cloud.githubusercontent.com/assets/13019449/25551469/053f8fec-2c8e-11e7-8e30-1bd16468fedc.png)

**Comment by TaoistKing** [comment]
@volokha  Text/Voice is Not supported right now, I will update the code when I have time.
If you need voice functions, just change the media constraints to voice only when you create offer/answer.

**Comment by volokha** [comment]
Thanks for your reply!
